import type { DemoScript } from "./types";

export const demoScripts: DemoScript[] = [
  {
    id: "script-gentle-trap",
    slug: "gentle-trap",
    title: "温柔陷阱",
    subtitle: "一段关系里，最危险的不是坏人露出獠牙，而是他一直很温柔。",
    description:
      "林夏在陌生城市独自生活。周予安出现得恰到好处：记得她的喜好，接住她的疲惫，也慢慢让她怀疑身边真正关心她的人。玩家要在一段看似浪漫的关系里识别试探、保留证据，并决定是否及时止损。",
    theme: "女性成长 / 情感反诈",
    style: "现实、悬疑、克制、漫画短剧",
    tags: ["女性成长", "反诈", "情感操控", "现实题材"],
    targetAudience: "18 岁以上用户",
    contentWarning:
      "包含情绪操控、金钱风险和关系压力等内容，用于风险教育和互动体验。",
    accessPassword: "123456",
    status: "published",
    estimatedMinutes: 18,
    planning: {
      logline:
        "一个年轻女生在温柔关系中识别情绪操控和金钱骗局，靠边界、证据和朋友完成自救。",
      playerGoal: "保持清醒，识别危险信号，避免经济损失，建立求助意识。",
      mainConflict: "渴望被坚定选择，和保持自我边界之间的冲突。",
      tone: "前半段温柔暧昧，后半段压迫感逐渐浮出水面。",
      safetyBoundary:
        "不提供诈骗教程，不美化操控关系，不指责受害者，强调止损、求助和证据意识。",
    },
    stats: [
      {
        key: "clarity",
        name: "清醒值",
        description: "识别风险和保持边界的能力。",
        initialValue: 48,
        visible: true,
      },
      {
        key: "trust",
        name: "信任值",
        description: "对风险对象的信任程度。",
        initialValue: 42,
        visible: true,
      },
      {
        key: "economicRisk",
        name: "经济风险",
        description: "金钱损失和被继续加码的风险。",
        initialValue: 10,
        visible: true,
      },
      {
        key: "socialSupport",
        name: "社交支持",
        description: "朋友、家人和外部帮助是否仍在身边。",
        initialValue: 52,
        visible: true,
      },
      {
        key: "evidence",
        name: "证据完整度",
        description: "聊天记录、转账凭证和身份核实材料的完整程度。",
        initialValue: 8,
        visible: true,
      },
    ],
    characters: [
      {
        id: "heroine",
        key: "heroine",
        name: "林夏",
        roleType: "protagonist",
        description: "25 岁，刚进入城市工作，独立生活，习惯把难处先吞下去。",
        personality: "敏感、认真、容易心软，但不是没有判断力。",
        narrativeFunction: "玩家代入角色，承担判断和选择。",
        defaultAssetId: "heroine-calm",
      },
      {
        id: "zhou",
        key: "zhou",
        name: "周予安",
        roleType: "risk_object",
        description: "成熟体贴的外表下，逐渐用情绪和信任测试推进控制。",
        personality: "温柔、会共情、回避具体问题，压力下会转向指责。",
        narrativeFunction: "呈现亲密关系中的危险信号和金钱试探。",
        defaultAssetId: "zhou-gentle",
      },
      {
        id: "xuran",
        key: "xuran",
        name: "许然",
        roleType: "ally",
        description: "林夏的闺蜜，话不多但看事很准。",
        personality: "敏锐、行动派、保护朋友但不替朋友做决定。",
        narrativeFunction: "提供外部视角和求助路径。",
        defaultAssetId: "xuran-alert",
      },
    ],
    assets: [
      {
        id: "cover-gentle-trap",
        key: "cover-gentle-trap",
        name: "剧本封面",
        type: "cover",
        fileUrl: "/assets/demo/cover-gentle-trap.svg",
        status: "approved",
      },
      {
        id: "apartment-night",
        key: "apartment-night",
        name: "出租屋雨夜",
        type: "background",
        fileUrl: "/assets/demo/bg-apartment-night.svg",
        status: "approved",
      },
      {
        id: "phone-chat",
        key: "phone-chat",
        name: "聊天记录",
        type: "background",
        fileUrl: "/assets/demo/bg-phone-chat.svg",
        status: "approved",
      },
      {
        id: "cafe-evening",
        key: "cafe-evening",
        name: "街角咖啡馆",
        type: "background",
        fileUrl: "/assets/demo/bg-cafe-evening.svg",
        status: "approved",
      },
      {
        id: "heroine-calm",
        key: "heroine-calm",
        name: "林夏-冷静",
        type: "expression",
        fileUrl: "/assets/demo/char-heroine-calm.svg",
        characterId: "heroine",
        emotion: "calm",
        pose: "phone",
        status: "approved",
      },
      {
        id: "heroine-worried",
        key: "heroine-worried",
        name: "林夏-犹豫",
        type: "expression",
        fileUrl: "/assets/demo/char-heroine-worried.svg",
        characterId: "heroine",
        emotion: "worried",
        pose: "phone",
        status: "approved",
      },
      {
        id: "zhou-gentle",
        key: "zhou-gentle",
        name: "周予安-温柔",
        type: "expression",
        fileUrl: "/assets/demo/char-zhou-gentle.svg",
        characterId: "zhou",
        emotion: "gentle",
        pose: "standing",
        status: "approved",
      },
      {
        id: "zhou-cold",
        key: "zhou-cold",
        name: "周予安-冷淡",
        type: "expression",
        fileUrl: "/assets/demo/char-zhou-cold.svg",
        characterId: "zhou",
        emotion: "cold",
        pose: "standing",
        status: "approved",
      },
      {
        id: "xuran-alert",
        key: "xuran-alert",
        name: "许然-警觉",
        type: "expression",
        fileUrl: "/assets/demo/char-xuran-alert.svg",
        characterId: "xuran",
        emotion: "alert",
        pose: "standing",
        status: "approved",
      },
    ],
    nodes: [
      {
        id: "opening",
        key: "opening",
        title: "雨夜来信",
        nodeType: "start",
        chapter: "初遇",
        summary: "林夏在疲惫的雨夜收到周予安的消息。",
        goal: "建立女主的孤独处境和男方过于精准的体贴。",
        tone: "安静、疲惫、被理解的轻微暖意。",
        backgroundAssetId: "apartment-night",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-calm", position: "left" },
          { characterId: "zhou", assetId: "zhou-gentle", position: "right" },
        ],
        statDelta: {},
        narration:
          "雨从窗沿往下淌。林夏把湿掉的鞋踢到门边，刚想关灯，手机亮了。周予安发来一张便利店热牛奶的照片，配了一句：给你留了一瓶，明天别空腹上班。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "gentle",
            text: "你今天没吃晚饭吧。别逞强，我猜你又是最后一个走。",
          },
          {
            speaker: "heroine",
            emotion: "calm",
            text: "你怎么每次都猜得这么准？",
          },
        ],
        choices: [
          {
            id: "accept-care",
            text: "回他：谢谢，你真懂我",
            description: "被照顾的感觉让关系升温。",
            nextNodeId: "cafe-date",
            statDelta: { trust: 9, clarity: -3 },
          },
          {
            id: "keep-distance",
            text: "只回一句谢谢，然后休息",
            description: "保留一点距离，给自己恢复空间。",
            nextNodeId: "cafe-date",
            statDelta: { clarity: 6, trust: -2 },
          },
        ],
      },
      {
        id: "cafe-date",
        key: "cafe-date",
        title: "刚刚好的座位",
        nodeType: "event",
        chapter: "升温",
        summary: "周予安安排了一场看似自然的咖啡馆见面。",
        goal: "让温柔变得具体，同时埋下控制的第一根线。",
        tone: "暧昧、精心安排、表面舒服。",
        backgroundAssetId: "cafe-evening",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-calm", position: "left" },
          { characterId: "zhou", assetId: "zhou-gentle", position: "right" },
        ],
        statDelta: {},
        narration:
          "咖啡馆靠窗的位置像是提前为她空出来的。杯垫下面压着一张电影票，时间刚好是她加班结束后半小时。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "gentle",
            text: "我没有查你行程，只是记得你说过周五会轻松一点。",
          },
          {
            speaker: "heroine",
            emotion: "calm",
            text: "你记性也太好了。",
          },
        ],
        choices: [
          {
            id: "enjoy-date",
            text: "接受这份安排",
            description: "浪漫感增强，也更容易忽略细节。",
            nextNodeId: "friend-warning",
            statDelta: { trust: 10, clarity: -5 },
          },
          {
            id: "ask-source",
            text: "问他怎么知道下班时间",
            description: "温和确认边界。",
            nextNodeId: "friend-warning",
            statDelta: { clarity: 8, evidence: 4, trust: -2 },
          },
        ],
      },
      {
        id: "friend-warning",
        key: "friend-warning",
        title: "许然的提醒",
        nodeType: "normal",
        chapter: "隔离",
        summary: "许然提醒林夏，周予安知道的信息太多。",
        goal: "引入外部视角，并让玩家决定是否保留社交支持。",
        tone: "日常对话里出现第一道裂缝。",
        backgroundAssetId: "phone-chat",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-worried", position: "left" },
          { characterId: "xuran", assetId: "xuran-alert", position: "right" },
        ],
        statDelta: {},
        narration:
          "许然听完咖啡馆的事，没有像往常那样开玩笑。她只让林夏把聊天记录往上翻，从第一天开始看。",
        dialogues: [
          {
            speaker: "xuran",
            emotion: "alert",
            text: "体贴不是问题。问题是，他好像总能知道你什么时候最脆弱。",
          },
          {
            speaker: "heroine",
            emotion: "worried",
            text: "你是不是想多了？他对我挺好的。",
          },
        ],
        choices: [
          {
            id: "keep-friend",
            text: "把聊天记录留给许然看",
            description: "让朋友帮你从外部观察。",
            nextNodeId: "isolation",
            statDelta: { socialSupport: 14, clarity: 8, evidence: 7 },
            isKeyChoice: true,
          },
          {
            id: "hide-from-friend",
            text: "替周予安解释，结束话题",
            description: "关系更私密，但外部提醒变弱。",
            nextNodeId: "isolation",
            statDelta: { trust: 8, socialSupport: -12, clarity: -7 },
          },
        ],
      },
      {
        id: "isolation",
        key: "isolation",
        title: "你不用什么都告诉她",
        nodeType: "event",
        chapter: "隔离",
        summary: "周予安开始轻描淡写地否定许然。",
        goal: "呈现隔离关系网的早期话术。",
        tone: "温柔表面下的占有和不悦。",
        backgroundAssetId: "apartment-night",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-worried", position: "left" },
          { characterId: "zhou", assetId: "zhou-gentle", position: "right" },
        ],
        statDelta: {},
        narration:
          "那晚，周予安第一次没有说晚安。他问她是不是把两个人的事都告诉了许然，语气仍旧温柔，却比窗外的雨更凉。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "gentle",
            text: "她不了解我，也不了解我们。你把所有事都拿去问她，我会觉得自己像个外人。",
          },
          {
            speaker: "heroine",
            emotion: "worried",
            text: "我只是想听听她的意见。",
          },
        ],
        choices: [
          {
            id: "name-boundary",
            text: "告诉他：朋友不是威胁",
            description: "明确边界，观察他的反应。",
            nextNodeId: "first-borrow",
            statDelta: { clarity: 12, socialSupport: 6, trust: -5 },
            isKeyChoice: true,
          },
          {
            id: "apologize",
            text: "向他道歉，答应少说",
            description: "暂时换来和好，但边界后退。",
            nextNodeId: "first-borrow",
            statDelta: { trust: 9, socialSupport: -10, clarity: -7 },
          },
        ],
      },
      {
        id: "first-borrow",
        key: "first-borrow",
        title: "第一笔周转",
        nodeType: "choice",
        chapter: "试探",
        summary: "周予安以资金周转为由第一次向林夏借钱。",
        goal: "呈现金钱试探、情绪施压和求证机会。",
        tone: "温柔撤退，压力出现。",
        backgroundAssetId: "phone-chat",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-worried", position: "left" },
          { characterId: "zhou", assetId: "zhou-cold", position: "right" },
        ],
        statDelta: {},
        narration:
          "周予安发来一段十七秒的语音。背景很安静，他停顿了两次，像是把难堪咽回去，才说出那句“你能不能先帮我垫一下”。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "cold",
            text: "不是大钱，只是项目款今天没到账。明天中午前还你。",
          },
          {
            speaker: "zhou",
            emotion: "cold",
            text: "你要是不方便就算了。我只是没想到，你会这么防着我。",
          },
        ],
        choices: [
          {
            id: "send-money",
            text: "立刻转钱，别让他难堪",
            description: "用钱证明信任，风险会快速升高。",
            nextNodeId: "bad-ending",
            statDelta: { economicRisk: 48, trust: 18, clarity: -20, evidence: -4 },
            isKeyChoice: true,
          },
          {
            id: "ask-details",
            text: "问清用途、金额和还款凭证",
            description: "不拒绝帮助，但要求信息透明。",
            nextNodeId: "details-pressure",
            statDelta: { clarity: 14, evidence: 12, trust: -5 },
            isKeyChoice: true,
          },
          {
            id: "ask-friend",
            text: "截图发给许然",
            description: "把问题带出二人关系。",
            nextNodeId: "evidence-route",
            statDelta: { socialSupport: 18, clarity: 13, evidence: 14, trust: -8 },
            isKeyChoice: true,
          },
        ],
      },
      {
        id: "details-pressure",
        key: "details-pressure",
        title: "问题越问越冷",
        nodeType: "event",
        chapter: "试探",
        summary: "林夏追问细节后，周予安开始把问题转成感情测试。",
        goal: "让玩家看到回避细节和情绪勒索的区别。",
        tone: "冷下来、压迫、关系测试。",
        backgroundAssetId: "apartment-night",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-worried", position: "left" },
          { characterId: "zhou", assetId: "zhou-cold", position: "right" },
        ],
        statDelta: {},
        narration:
          "她只是问了转账用途和还款时间。周予安的回复却隔了很久，久到屏幕暗下去三次。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "cold",
            text: "我现在最难的时候，你第一反应是让我写借条。",
          },
          {
            speaker: "heroine",
            emotion: "worried",
            text: "我不是不帮你，我只是想把事情说清楚。",
          },
        ],
        choices: [
          {
            id: "give-in",
            text: "不再追问，直接转钱",
            description: "关系暂时和好，经济风险失控。",
            nextNodeId: "bad-ending",
            statDelta: { economicRisk: 40, trust: 12, clarity: -16, evidence: -5 },
          },
          {
            id: "hold-line",
            text: "坚持要书面说明",
            description: "让对方暴露更多矛盾。",
            nextNodeId: "evidence-route",
            statDelta: { clarity: 16, evidence: 18, trust: -10 },
            isKeyChoice: true,
          },
        ],
      },
      {
        id: "evidence-route",
        key: "evidence-route",
        title: "证据链",
        nodeType: "ending",
        chapter: "反击",
        summary: "林夏保留证据并暂停转账，在朋友帮助下核实风险。",
        goal: "给出正向结局：冷静、求助、止损。",
        tone: "紧张后转向清醒和稳定。",
        backgroundAssetId: "cafe-evening",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-calm", position: "left" },
          { characterId: "xuran", assetId: "xuran-alert", position: "right" },
        ],
        statDelta: { clarity: 12, socialSupport: 10, evidence: 20 },
        narration:
          "许然没有替她做决定，只是陪她把聊天记录、语音、转账要求和他的身份信息一条条列出来。那些曾经被温柔包住的漏洞，终于露出了边缘。",
        dialogues: [
          {
            speaker: "xuran",
            emotion: "alert",
            text: "真正尊重你的人，不会用信任逼你放弃核实。",
          },
          {
            speaker: "heroine",
            emotion: "calm",
            text: "我先不转。我要把记录保存下来，也要问专业的人该怎么处理。",
          },
        ],
        choices: [],
      },
      {
        id: "bad-ending",
        key: "bad-ending",
        title: "温柔债务",
        nodeType: "ending",
        chapter: "沉没",
        summary: "林夏转钱后，对方继续以账户冻结和补款施压。",
        goal: "呈现错误选择的沉重后果，但避免指责受害者。",
        tone: "压抑、后悔、现实冲击。",
        backgroundAssetId: "phone-chat",
        characterBindings: [
          { characterId: "heroine", assetId: "heroine-worried", position: "left" },
          { characterId: "zhou", assetId: "zhou-cold", position: "right" },
        ],
        statDelta: { economicRisk: 30, clarity: -10, socialSupport: -8 },
        narration:
          "第一笔钱转出去后，事情没有变好。新的理由一条接一条：账户冻结、临时保证金、再补一笔就能全部退回。林夏盯着余额，终于意识到自己不是在帮一个爱人，而是在被一套话术推着往前走。",
        dialogues: [
          {
            speaker: "zhou",
            emotion: "cold",
            text: "现在停下，前面的钱就真的白费了。你再信我一次。",
          },
          {
            speaker: "heroine",
            emotion: "worried",
            text: "我明明只是想相信你，为什么每一步都变成我必须证明自己？",
          },
        ],
        choices: [],
      },
    ],
    aiJobs: [
      {
        id: "job-outline",
        jobType: "script_outline",
        status: "applied",
        title: "生成剧本策划案",
        description: "根据女性情感反诈主题生成策划案。",
        outputPreview: "已生成 logline、主题目标、内容边界和节点数量建议。",
      },
      {
        id: "job-assets",
        jobType: "asset_plan",
        status: "completed",
        title: "生成美术资源需求",
        description: "生成背景、角色表情和关键道具需求。",
        outputPreview: "建议 7 张背景、3 名主要角色、31 张角色差分、6 张道具图。",
      },
      {
        id: "job-check",
        jobType: "consistency_check",
        status: "completed",
        title: "一致性检查",
        description: "检查节点引用、分支断链和安全边界。",
        outputPreview: "未发现断链；建议补充发布页内容提示。",
      },
    ],
  },
];

export function getScriptBySlug(slug: string) {
  return demoScripts.find((script) => script.slug === slug);
}

export function getScriptByIdOrSlug(idOrSlug: string) {
  return demoScripts.find(
    (script) => script.id === idOrSlug || script.slug === idOrSlug,
  );
}
